### ISSUE TITLE
Elkstack version 6

### ISSUE THREAD

**Issue by Beast12** [OutsideIT/logstash_filter_f5#3]
Hi,
Thanks for the great effort you are doing for this. But I noticed that the template you added now, isn't compatible with ES 6. 
Are there any plans to update everything to be compatible with Version 6?

**Comment by willemdh** [comment]
@Beast12 Hey actually I'm already using it with es 6. I should update the repo with my latest version, didn't realize some things are not compatible. Can you tell me what part exactly is not compatible?

**Comment by willemdh** [comment]
@Beast12 I actually already know what the issue is.. It's the template directive that is changes with the index_pattern directive. I pushed my latest template version, let me know if that works for you.

**Comment by Beast12** [comment]
Hi Willemdh,
Thanks for updating the template! No more errors now... I just have a question...
When I look in kibana now. I only have some info... As you can see in the screenshot, there is missing a lot of info. Is this something wrong in the F5 config or... I just copied your config for logstash (adding the correct path for the patterns and dictionary of course). I've got a lot of _grokparsefailures...
![f5](https://user-images.githubusercontent.com/5346327/38794841-b28fb608-4156-11e8-987b-1c48e2397971.png)

Kind regards

**Comment by willemdh** [comment]
@Beast12 Well I've talked about this with multiple F5 admins and there might be some small differences between version or used settings. I'm leaving on a holiday now for 2 weeks, I'll try to find some time (not making any promises though) to check where the issue might be. The logger syslog program in your document is actually not a very good example, as imho I didn't ever see very useful info coming out of that. But apm, apd, dcc and tmm are also throwing _grokparsefailures? I sent you an invite to OutsideIT team, where we can discuss this further, visit https://github.com/OutsideIT to accept the invitation.

**Comment by Beast12** [comment]
@willemdh Thanks!! I've accepted the invitation. Tomorrow we have a F5 consultant with us. I will check with him also.
Big thanks for your help!!! I will close this issue now for the original problem has been fixed
